### ISSUE TITLE
CORS Error with CAS Actions

### ISSUE THREAD

**Issue by mschubert90** [sassoftware/restaf-uidemos#15]
Hey Deva,

we installed the new Viya Update and are now getting another CORS Error, since last time we got "No 'Access-Control-Allow-Origin' header is present" we got now after the update the following Error:
![cors error](https://user-images.githubusercontent.com/98527783/175521808-349446b0-9e26-4d95-b17b-201ebb13c387.png)
We tried to add the controller URL to the "Access-Control-Allow-Origin" but still get the CORS Error.

Any ideas how to fix this?

Thank you and kind regards
Max

**Comment by devaKumaraswamy** [comment]
@mschubert90  The fix for this issue **did not** make this release. It appears they found an issue during the pre-release testing. Sorry for misleading you on the timeline. 

Can you do me a favor? can you contact SAS Tech Support and send the details of the error? I think they have some open tickets on this. Documenting the issue. 

I will see which earlier stable release does not have this issue.

I will leave this issue open until the fix is released.

Once again, sorry for the inconvenience.
Deva

**Comment by mschubert90** [comment]
Thank you for your reply! I contacted the SAS Tech Support with the details of the error. 

Do you already know if the bug will be fixed with the next release?

Kind regards
Max

**Comment by devaKumaraswamy** [comment]
I believe so.  Thanks for your patience

**Comment by devaKumaraswamy** [comment]
I will leave this open until the fixed version is released

**Comment by devaKumaraswamy** [comment]
Closing this since there are instructions on how to configure CAS server manually.  This is documented here: 
 https://sassoftware.github.io/restaf/tutorial-usefulTips.html
